/*

 PELLET.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Pellet[] =
{
  0x36,0x36,0x08,0x08,0x1C,0x1C,0x2A,0x26,
  0x3A,0x26,0x14,0x1C,0x08,0x08,0x00,0x00
};

/* End of PELLET.C */
